# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'CodeLeg.com'
tagline:             'The Data Science and Algorithm Design Blog'
description:         'Howdy, I am Bosah Chude, a Data Scientist and Software Developer at <a href="http://www.belfox.net/">Belfox Technologies</a>.<br/><br/>Here, I scribble away my toughts as my legs take me into the world of code.'
url:                 'https://codeleg.com'
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              'Bosah Chude'
  url:               'https://ng.linkedin.com/in/bosahchude'
  email:             'chude@codeleg.com'

# Custom vars
version:             1.0.0

# Dependencies
gems:                [jekyll-paginate]

# Social Info
github:              'https://github.com/bosahchude/'
linkedin:            'https://ng.linkedin.com/in/bosahchude'
